apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/javisolispro/argocd-app-config.git
        revision: HEAD
        files:
          - path: "**/config.json"
  template:
    metadata:
      name: "{{appName}}"
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: https://github.com/javisolispro/argocd-app-template.git
          targetRevision: HEAD
          path: "{{chart}}"
          helm:
            valueFiles:
              - $config/{{appName}}/values.yaml
        - repoURL: https://github.com/javisolispro/argocd-app-config.git
          targetRevision: HEAD
          ref: config
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
